select top 10000 '%2862'+CAST( tPlayer .PlayerId  AS VARCHAR(10))+'?' as PlayerId,tPlayerIdentType .PlayerIdentity , tPlayerCard .Acct ,tPlayer.FirstName ,tPlayer.LastName
from tPlayer ,tPlayerCard ,tPlayerIdentType
where tPlayer .PlayerId = tPlayerCard .PlayerId and
tPlayer .PlayerId = tPlayerIdentType .PlayerId
--and tPlayerCard .Acct = '100014240'
// Boletas
 exec spGetAwardActivityHourPoints @CasinoID=N'1',@PlayerID=10003152,@AccumulatorPeriod=N'H',@ShowAvgBetTime=0,@ShowByDepartment=1,@DebugLevel=0,@IsTierPoint=0
/*select tPlayer .PlayerId  as PlayerId,tPlayerIdentType .PlayerIdentity , tPlayerCard .Acct ,tPlayer.FirstName ,tPlayer.LastName
from tPlayer ,tPlayerCard ,tPlayerIdentType
where tPlayer .PlayerId = tPlayerCard .PlayerId and
tPlayer .PlayerId = tPlayerIdentType .PlayerId and tPlayerCard .Acct = '100018661'*/

SELECT
    *
FROM
    (
    SELECT
        TM.SDS_ACCOUNT_NUMBER,
        TM.TRANS_TYPE_DESC,
        TM.CMS_PLAYER_ID,
        ROW_NUMBER() OVER(
    ORDER BY
        FS_TIME
    DESC
    ) AS ROWNUM,
    TM.TRMA_TRANSACTION_LOGID,
    TM.FS_SLOT_NUMBER AS FS_SLOT_NUMBER,
    TM.FS_STAND_NUMBER AS FS_STAND_NUMBER,
    TM.FS_INT_SLOT AS FS_INT_SLOT,
    TM.TRMA_LINE_ADDRESS AS FS_LINE_ADDR,
    TM.TRMA_SITE_ID AS VTRANS_SITEID,
    TM.FS_TIME,
    TM.TRMA_IS_EXTENDED_MSG AS FS_EXT_MSG,
    CASE WHEN UPPER(TM.TRMA_IS_EXTENDED_MSG) = 'Y' THEN '~' ELSE ' '
        END AS XTND_MSG,
        CASE WHEN TM.STDA_DOOR_STATUS IN(4, 5, 6, 7, 12, 13, 14, 15) THEN '*' ELSE ' '
END AS DOOR_STATUS,
CASE WHEN TM.EVMA_EXCEPTION_CODE IN(307, 308, 309) THEN 185 ELSE TM.EVMA_EXCEPTION_CODE
END AS FS_EXC_CODE,
CASE WHEN TM.EVMA_EVENT_ID IN(115, 116) THEN(
    SGE.SGE_DROP_TYPE + '-' + TM.EVMA_EVENT_NAME
) ELSE TM.EVMA_EVENT_NAME
END AS FS_EXCEPTION_CODE_DESCRIPTION,
TM.STDA_EMPLOYEE_NAME AS FS_EMPLOYEE_NAME,
TM.STDA_EMPLOYEE_CARDNUM AS FS_EMPLOYEE_ID,
TM.STDA_EMPLOYEE_ID AS FS_EMP_ID,
TM.STDA_PLAYER_CARDNUM AS FS_PLAYER_ID,
TM.STDA_BONUS_POINTS AS FS_BONUS,
TM.STDA_OPTION_BYTE AS FS_OPT,
TM.STDA_BONUS_CNTDWN AS FS_CNT_DOWN,
TM.STDA_CASINO_ID AS FS_CAS_ID,
TM.STDA_SMI_CODE AS FS_MANU_SMI_CODES,
TM.STDA_MESSAGE_SEQUENCE AS FS_MSG_SQ,
TM.TRMA_TRANSACTION_ID AS FS_TRN_ID,
UPPER(TM.STDA_JACKPOT_ID) AS FS_JPID,
TM.STDA_IDFROM_PLYR_CARDNUM AS FS_IDFROM_PLYR_CARDNUM,
CASE WHEN TM.STDA_GMU_DENOM = 0 THEN 0 WHEN TM.STDA_GMU_DENOM IS NULL THEN NULL WHEN TM.EVMA_EXCEPTION_CODE = 10 THEN CAST(TM.JAME_HANDPAID_JP AS FLOAT) / TM.STDA_GMU_DENOM / 100
END AS FS_FILL_APJP,
CAST(
    TM.STDA_JACKPOT_AMOUNT AS FLOAT
) / 100 AS FS_JACKPOT_AMOUNT,
UPPER(SGE.SGE_JACKPOT_ID) AS FS_JPID_SYS,
CAST(SGE.SGE_NORMAL_JP_AMT AS FLOAT) / 100 AS FS_SYS_GEN_JKT_AMT,
CAST(SGE.SGE_CC_JP_AMT AS FLOAT) / 100 AS FS_SYS_GEN_JKT_AMT_FE,
CAST(SGE.SGE_PROG_JP_AMT AS FLOAT) / 100 AS FS_PROGJP_AMT,
CAST(SGE.SGE_DISPUTE_AMT AS FLOAT) / 100 AS FS_BEEF_POSTED,
SR.STSF_ID AS FS_SLIP_FLAG,
TM.COME_BETS AS FS_COIN_IN,
TM.COME_WINS AS FS_COIN_OUT,
TM.COME_PLAYS AS FS_HANDPULLS,
TM.COME_BETS_SIZE AS FS_COIN_IN_SIZE,
TM.COME_WINS_SIZE AS FS_COIN_OUT_SIZE,
TM.COME_PLAYS_SIZE AS FS_HANDPULLS_SIZE,
TM.JAME_MACHPAID_PROGJP AS FS_MACH_PD_PRG,
TM.AI_ALERT_NUMBER AS FS_CB_MSG,
CAST(TM.TKT_AMOUNT AS FLOAT) / 100 AS FS_TICKET_AMOUNT,
TM.TKT_STAT_DESCRIPTION AS FS_TICKET_STATUS,
TM.TKT_TYPE_ID AS FS_TICKET_TYPEID,
TM.TKT_AMT_TYPE_ID AS FS_AMOUNT_TYPEID,
TM.TKT_ERROR_CODE AS FS_TICKET_ERROR,
TM.TKT_STATUS_ID AS FS_STATUS_ID,
CASE TM.TKT_STATUS_ID WHEN 3 THEN TM.TKT_BARCODE ELSE CASE WHEN TM.TKT_TYPE_ID != 6 THEN LEFT(TM.TKT_BARCODE, 14) + ' *** ' + RIGHT(TM.TKT_BARCODE, 1) ELSE LEFT(TM.TKT_BARCODE, 10) + ' *** ' + RIGHT(TM.TKT_BARCODE, 5)
END
END AS FS_TICKET_NUMBER,
TM.TKT_TRANS_DESCRIPTION AS FS_ERROR_DESC,
ASST_INFO.FS_AREA_ID AS FS_AREA_ID,
ASST_INFO.FS_ASSET_SLOT_NUMBER AS FS_ASSET_SLOT_NUMBER,
ASST_INFO.FS_ASSET_STAND_NUMBER AS FS_ASSET_STAND_NUMBER,
ASST_INFO.FS_AREA AS FS_AREA,
ASST_INFO.FS_TYPE_DESCRIPTION AS FS_TYPE_DESCRIPTION,
ASST_INFO.FS_PROTOCOL_VERSION AS FS_PROTOCOL_VERSION,
ASST_INFO.FS_GMU_EPROM_ID AS FS_GMU_EPROM_ID,
ASST_INFO.FS_GMU_DOC_ID AS FS_GMU_DOC_ID,
ASST_INFO.FS_GMU_DENOM AS FS_GMU_DENOM,
ASST_INFO.FS_MULTI_DENOM AS FS_MULTI_DENOM,
ASST_INFO.FS_DENOMINATION AS FS_DENOMINATION,
ASST_INFO.FS_STATUS AS FS_STATUS,
ASST_INFO.FS_MFR AS FS_MFR
FROM
    (
    SELECT AT
        .ATRN_ACNT_NO AS SDS_ACCOUNT_NUMBER,
        ATT.ACNT_TRANS_TYPE_DESC AS TRANS_TYPE_DESC,
        ACNT.ACNT_CMS_PLAYER_ID AS CMS_PLAYER_ID,
        TMM.TRMA_SITE_ID AS TRMA_SITE_ID,
        TMM.TRMA_TRANSACTION_LOGID,
        CAST(TMM.TRMA_ACNF_NUMBER AS INT) AS FS_INT_SLOT,
        TMM.TRMA_ACNF_NUMBER,
        TMM.TRMA_ACNF_LOCATION AS FS_STAND_NUMBER,
        TMM.TRMA_LINE_ADDRESS,
        TMM.TRMA_ACNF_NUMBER AS FS_SLOT_NUMBER,
        TMM.TRMA_IS_EXTENDED_MSG,
        CASE WHEN LOWER(VGST.S_VALUE) = 'yes' THEN TMM.TRMA_GAME_DATETIME ELSE TMM.TRMA_REQUEST_DATETIME
END AS FS_TIME,
TMM.TRMA_MESSAGE_ID,
TMM.TRMA_AREA_ID,
TMM.STDA_PLAYER_CARDNUM,
EM.EVMA_EXCEPTION_CODE,
EM.EVMA_EVENT_NAME,
EM.EVMA_EVENT_ID,
TMM.STDA_DOOR_STATUS,
TMM.STDA_BONUS_POINTS,
TMM.STDA_OPTION_BYTE,
TMM.STDA_BONUS_CNTDWN,
TMM.STDA_CASINO_ID,
TMM.STDA_SMI_CODE,
TMM.STDA_EMPLOYEE_NAME,
TMM.STDA_EMPLOYEE_CARDNUM,
TMM.STDA_JACKPOT_ID,
TMM.STDA_JACKPOT_AMOUNT,
TMM.STDA_EMPLOYEE_ID,
TMM.STDA_IDFROM_PLYR_CARDNUM,
TMM.STDA_GMU_DENOM,
TMM.STDA_MESSAGE_SEQUENCE,
TMM.TRMA_TRANSACTION_ID,
TMM.COME_BETS,
TMM.COME_WINS,
TMM.COME_PLAYS,
TMM.JAME_MACHPAID_PROGJP,
TMM.AI_ALERT_NUMBER,
TMM.TKT_AMOUNT,
TMM.TKT_STAT_DESCRIPTION,
TMM.TKT_TYPE_ID,
TMM.TKT_AMT_TYPE_ID,
TMM.TKT_ERROR_CODE,
TMM.TKT_STATUS_ID,
TMM.TKT_BARCODE,
TMM.TKT_TRANS_DESCRIPTION,
TMM.JAME_HANDPAID_JP,
MTR.COME_BETS_SIZE,
MTR.COME_WINS_SIZE,
MTR.COME_PLAYS_SIZE
FROM
    [ TRANSACTION ].TRANSACTION_MASTER TMM
INNER JOIN [ TRANSACTION ].EVENT_MASTER EM
ON
    TMM.EVMA_EVENT_ID = EM.EVMA_EVENT_ID AND EM.EVMA_PROCESS_FLAG = 'Y' AND EM.EVMA_EXCEPTION_CODE NOT IN(0) AND TMM.TRMA_REQUEST_DATETIME BETWEEN '2017-11-16 13:00:20.0' AND '2017-11-17 02:41:37.0'
LEFT OUTER JOIN [ TRANSACTION ].METER_INFO MTR
ON
    TMM.TRMA_SITE_ID = MTR.SITE_NUMBER AND TMM.TRMA_ACNF_NUMBER = MTR.ACNF_NUMBER
INNER JOIN [ REPORT ].[ VIEW_TRANS_GAME_OR_SYS_TIME ] AS VGST
ON
    TMM.TRMA_SITE_ID = VGST.S_SITE_NUM
LEFT JOIN ECASH.ACCOUNT_TRANS AT
ON AT
    .ATRN_MSG_ID = TMM.TRMA_MESSAGE_ID
LEFT JOIN ECASH.ACCOUNT_TRANS_TYPE ATT
ON
    att.ACNT_TRANS_TYPE_ID = AT.ATRN_TRANS_TYPE_ID
LEFT JOIN ECASH.ACCOUNT ACNT
ON
    acnt.ACNT_NO = AT.ATRN_ACNT_NO
WHERE
    TMM.TRMA_SITE_ID IN(286) AND TMM.TRMA_ACNF_NUMBER IN('11401','11402','11403','11404')
) AS TM
LEFT OUTER JOIN [ TRANSACTION ].SYS_GEN_EXCEP AS SGE
ON
    SGE.TRMA_TRANSACTION_LOGID = TM.TRMA_TRANSACTION_LOGID
LEFT OUTER JOIN(
    SELECT SITE_NUMBER AS SITE_NUMBER,
        AREA_ID AS FS_AREA_ID,
        ACNF_NUMBER AS FS_ASSET_SLOT_NUMBER,
        ACNF_LOCATION AS FS_ASSET_STAND_NUMBER,
        ACNF_ADDRESS AS FS_ASSET_LINE_ADDRESS,
        AREA_LONG_NAME AS FS_AREA,
        TYPE_DESC AS FS_TYPE_DESCRIPTION,
        PROTOCOL_VERSION AS FS_PROTOCOL_VERSION,
        EPROM_ID AS FS_GMU_EPROM_ID,
        GMU_DOC_ID AS FS_GMU_DOC_ID,
        DENOMINATION AS FS_DENOMINATION,
        GMU_DENOM AS FS_GMU_DENOM,
        MULTI_DENOM AS FS_MULTI_DENOM,
        ACST_LONG_NAME AS FS_STATUS,
        MANF_LONG_NAME AS FS_MFR
    FROM
        [ TRANSACTION ].ASSET_DETAILS
    WHERE
        ACNF_NUMBER IN('11401')
) AS ASST_INFO
ON
    ASST_INFO.FS_ASSET_SLOT_NUMBER = TM.TRMA_ACNF_NUMBER AND ASST_INFO.SITE_NUMBER = TM.TRMA_SITE_ID
LEFT JOIN SLIP.SLIP_REFERENCE SR
ON
    SR.SLPR_MESSAGE_ID = TM.TRMA_MESSAGE_ID) AS FINAL_QUERY
ORDER BY
    FS_INT_SLOT ASC,
    FS_TIME ASC,
    FS_ASSET_STAND_NUMBER ASC